---
abstract: 'update your Subversion repository after release'
author:
  - 'Mark Gardner <mjgardner@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Subversion
recommends:
  Dist::Zilla::Plugin::Repository: 0
  Readonly::XS: 0
requires:
  Cwd: 0
  Dist::Zilla: 0
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::Plugin: 0
  Dist::Zilla::Role::Releaser: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Modern::Perl: 0
  Moose: 0
  Moose::Role: 0
  MooseX::Types::URI: 0
  Path::Class: 0
  Readonly: 0
  Regexp::DefaultFlags: 0
  SVN::Client: 0
  SVN::Repos: 0
  SVN::Wc: 0
  Test::Moose: 0
  Test::More: 0
  Test::Most: 0
  Text::Template: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Subversion
  repository: http://github.com/mjg/Dist-Zilla-Plugin-Subversion
version: 1.100890
